### ISSUE TITLE
policy not persisted in k8s - "substring not found"

### ISSUE THREAD

**Issue by felixkrohn** [JAORMX/selinux-k8s#1]
I'm running selinux-policy-helper-operator which in turn is calling selinux-k8s when pods are being annotated accordingly. This works well so far, but I'm seeing crashes on selinux-k8s invocation:
The first part, generation of a SELinux policy, seems to work fine and a .cil file is being written out - from my basic understanding of the code, this file is then meant to be read in, the poilicy extracted and persisted in ocp/k8s, but:

```
$ oc logs selinux-k8s-230f1b075a27eb46e8dfce33cdbb18c6e66c4eac
Policy aide-ds-example-fileintegrity-49cv2-daemon created!
Please load these modules using:
# semodule -i aide-ds-example-fileintegrity-49cv2-daemon.cil /usr/share/udica/templates/base_container.cil
Restart the container with: "--security-opt label=type:aide-ds-example-fileintegrity-49cv2-daemon.process" parameter
None
Traceback (most recent call last):
File "/usr/local/bin/selinuxk8s", line 11, in
load_entry_point('selinux-k8s==0.1.0', 'console_scripts', 'selinuxk8s')()
File "/usr/local/lib/python3.7/site-packages/selinux_k8s-0.1.0-py3.7.egg/selinux_k8s/selinux_k8s.py", line 175, in main
File "/usr/local/lib/python3.7/site-packages/selinux_k8s-0.1.0-py3.7.egg/selinux_k8s/selinux_k8s.py", line 141, in get_inner_policy
ValueError: substring not found
```

The generated policy file looks fine to me:
```
sh-5.0# head -n3 aide-ds-example-fileintegrity-49cv2-daemon.cil
(block aide-ds-example-fileintegrity-49cv2-daemon
(blockinherit container)
(allow process default_t ( dir ( open read getattr lock search ioctl add_name remove_name write )))
sh-5.0# tail -n3 aide-ds-example-fileintegrity-49cv2-daemon.cil
(allow process root_t ( file ( getattr read write append ioctl lock map open create  )))
(allow process root_t ( sock_file ( getattr read write append open  )))
)sh-5.0#
sh-5.0# 
sh-5.0# semodule -v -i aide-ds-example-fileintegrity-49cv2-daemon.cil /usr/share/udica/templates/base_container.cil
Attempting to install module 'aide-ds-example-fileintegrity-49cv2-daemon.cil':
Ok: return value of 0.
Attempting to install module '/usr/share/udica/templates/base_container.cil':
Ok: return value of 0.
Committing changes:
Ok: transaction number 9.
```
Do you have any pointers how to find out where the issue could reside?
Might the missing EOL in the policy file be causing trouble?

**Comment by JAORMX** [comment]
@felixkrohn haven't tried this code in a while now :) ... but from what I can tell, the cil file is not valid for some reason. this is where it fails:
```
    first_p_idx = policy.index("(")
```
If it's not able to find the first parenthesis, there's clearly something wrong here.

**Comment by JAORMX** [comment]
@felixkrohn we're gonna rework this whole thing (including the policy helper operator) to the Security Profiles Operator https://github.com/kubernetes-sigs/security-profiles-operator

**Comment by felixkrohn** [comment]
wow, thanks for that quick feedback!
Yes, that it couldn't read the policy was my first conclusion as well, but I don't understand why.
ok, so from I understand you'd rather recommend us using the new security-profiles-operator, as selinux-k8s/selinux-policy-helper-operator probably won't see any maintenance in the future?
Would you happen to know if and when security-profiles-operator is meant to be supported by RH officially for Openshift 4.x?

**Comment by JAORMX** [comment]
None of this is supported. But I hope that in the future we can productive the SPO.
